version= 9.0

# set Theme to LIGHT or DARK
theme=DARK

#show.about=true
about.seconds=3

# properties folder
properties.path=./properties

# properties folder
properties.file=keyboard.properties

# when a device is available, it is selected automatically
# otherwise the application presents a dialog with a devices
# list,for selecting the good device
auto.select.device=true

# vendor file
vendor.file=vendor.properties
