version= 4.1

# set Theme to LIGHT or DARK
theme=LIGHT

show.about=true
about.seconds=3

# properties folder
properties.path=./properties

# when a device is available, it is selected automatically
# otherwise the application presents a dialog with a devices
# list,for selecting the good device
auto.select.device=true
