midi.path=./midi
midi.events.file=midievents.json
midi.demo.file=creative.mid

voices.path=./voices

# the directory to export files to
export.path=./export

# sysex
sysex.path=./sysex
sysex.events.file=sysexevents.json

# playlist
playlist.path=./playlist
playlist.file=playlist.json